[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "packinspect"
version = "1.0.0"
description = "Visual Anomaly Detection for Packaging Lines"
requires-python = "==3.10.*"